services:
  # postgres:
  #   image: postgres:16.4-alpine
  #   container_name: postgresql
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: vercel_clone
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  s3:
    image: localstack/localstack-s3-test:latest-s3
    container_name: localstack_s3
    ports:
      - "4566:4566"

volumes:
  postgres_data:
