services:
  postgres:
    image: postgres:16.4-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: replit_clone
    volumes:
      - postgres_data:/var/lib/postgresql/data

  s3:
    image: localstack/localstack-s3-test:latest-s3
    container_name: localstack_s3
    ports:
      - "4566:4566"

  runner:
    image: rohitshah1706/replit_runner:latest
    container_name: runner
    ports:
      - "1234:1234"
    environment:
      - WORKSPACE_PATH=/home/abc/workspace
      - UID=1001
      - AWS_S3_ENDPOINT=http://s3:4566
      - AWS_S3_BUCKET_NAME=replit-clone
      - AWS_S3_BUCKET_REGION=ap-south-1
      - AWS_EXPRESSAPP_USER_ACCESS_KEY=test
      - AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY=test

  api-service:
    image: rohitshah1706/replit_api_service:latest
    container_name: api_service
    ports:
      - "5000:5000"

  frontend:
    image: rohitshah1706/replit_frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
