apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
spec:
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      volumes:
        - name: logs-volume
          hostPath:
            path: /custom_logs
            type: DirectoryOrCreate
      containers:
        - name: api-service
          image: rohitshah1706/replit_api_service:latest
          env:
            - name: AWS_S3_ENDPOINT
              value: http://localstack-s3:4566
            - name: AWS_S3_BUCKET_NAME
              value: replit-clone
            - name: AWS_S3_BUCKET_REGION
              value: us-east-1
            - name: AWS_EXPRESSAPP_USER_ACCESS_KEY
              value: test
            - name: AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY
              value: test
            - name: K8S_NAMESPACE
              value: default
            - name: K8S_CONFIG_FILE_PATH
              value: ./kubeconfig/config
            - name: LOGS_PATH
              value: /home/node/custom_logs
          volumeMounts:
            - name: logs-volume
              mountPath: /home/node/
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-service
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  rules:
    - host: api-service.runner.local
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: api-service
                port:
                  number: 5000
