import dotenv from "dotenv";
dotenv.config();

const AWS_S3_ENDPOINT = process.env.AWS_S3_ENDPOINT || "";
const AWS_S3_BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME || "";
const AWS_S3_BUCKET_REGION = process.env.AWS_S3_BUCKET_REGION || "";
const AWS_EXPRESSAPP_USER_ACCESS_KEY =
  process.env.AWS_EXPRESSAPP_USER_ACCESS_KEY || "";
const AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY =
  process.env.AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY || "";
const K8S_NAMESPACE = process.env.K8S_NAMESPACE || "";
const K8S_CONFIG_FILE_PATH = process.env.K8S_CONFIG_FILE_PATH || "";
const NODE_ENV = process.env.NODE_ENV || "";
const LOGS_PATH = process.env.LOGS_PATH || "";

export {
  AWS_S3_ENDPOINT,
  AWS_S3_BUCKET_NAME,
  AWS_S3_BUCKET_REGION,
  AWS_EXPRESSAPP_USER_ACCESS_KEY,
  AWS_EXPRESSAPP_USER_SECRET_ACCESS_KEY,
  K8S_NAMESPACE,
  K8S_CONFIG_FILE_PATH,
  NODE_ENV,
  LOGS_PATH,
};
