apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-s3
  namespace: replit-app
spec:
  selector:
    matchLabels:
      app: localstack-s3
  template:
    metadata:
      labels:
        app: localstack-s3
    spec:
      containers:
        - name: localstack-s3
          image: localstack/localstack-s3-test:latest-s3
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4566
