- name: Deploying with Kubernetes
  hosts: all
  tasks:
    - name: Print the secrets file
      debug:
        msg: "{{ lookup('file', '../manifests/api-service/secrets_encrypted.yaml') | from_yaml }}"
